development:
  secret_key_base: 6ecd137cc35fb0eafd59d709303954469d8a10210a9f63d2b5ca2ccdec9813416a69a6a88b1ba7512a3fab5a179ef0268e53f8b1c5f5cea82e2c3e631f544634

test:
  secret_key_base: de9a2abe0603dcbe01d2c3f7f8d38b9c774fb98a6482f538aa04d1136d5c9658fa44c9055ac51fa0b57db54b9e086ab602e0869987ac245812b2ad92807b8d9d

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
