name: Build Docker Image test
on:
  push:
  schedule:
    - cron: '0 0 1 * *'
  issue_comment:
    types: [created]
jobs:
  test:
    concurrency:
      group: ${{ github.event.comment.id }}-${{ github.event_name }}-${{ github.ref_name == 'master' && github.sha || github.ref_name }}-build-test
      cancel-in-progress: true
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: Delete huge unnecessary tools folder
        run: |
          echo "${{ contains(fromJSON(vars.ALLOWED_ACTORS), github.event.author.login) }}"
          echo "${{ vars.ALLOWED_ACTORS }}"
          echo "${{ toJSON(github.event) }}"
          echo "${{ toJSON(github.event.author) }}"
          echo "${{ contains('phyzical,ArthurZheng,ritchiey,matthew-puku,rianniello,Kfoster14,waldofouche,Bo', github.event.author.login) }}"
